### ISSUE TITLE
Display appropriate message when there is no playlist added

### ISSUE THREAD

**Issue by janvi01** [janvi01/TuList#1]
Initially, when a user signs up, there is no playlist, or maybe the user deletes all the playlists, Display appropriate messages aligning with the UI. 

For eg:
"No playlist added, Add it now."

<img width="1792" alt="Screenshot 2024-03-13 at 10 16 36 PM" src="https://github.com/janvi01/TuList/assets/34344234/0e7ea823-2e46-47a7-b392-d1fcc975c812">

**Comment by PriyanshuPz** [comment]
Let me work on this issue @janvi01

**Comment by janvi01** [comment]
sure @priyanshuverma-dev go ahead.
